/** Plain-language notice for a personal portfolio demo. Edit freely. */

export type LegalSection = {
  heading: string;
  paragraphs: string[];
};

export const LEGAL_TITLE = "Privacy & terms";

export const LEGAL_INTRO =
  "This is a personal portfolio demo, not a commercial product. It exists so you can " +
  "try an agentic RAG pipeline and inspect how each answer was built. Please read this " +
  "short notice before you upload anything.";

export const LEGAL_SECTIONS: LegalSection[] = [
  {
    heading: "What this demo stores",
    paragraphs: [
      "Your email address, and a bcrypt hash of your password when you sign up with email. " +
        "The plain password is never stored.",
      "Your chats: titles, your questions, and the answers the agent produced.",
      "Your uploads: the original file, the text extracted from it, and the vector " +
        "embeddings used for search. Files are saved on the server disk under your account.",
    ],
  },
  {
    heading: "Third parties that process your content",
    paragraphs: [
      "Questions, chat history, and retrieved document excerpts are sent to the model " +
        "provider you use (OpenAI or Anthropic) so it can generate an answer.",
      "When the agent runs a web search, your search query is sent to Tavily.",
      "Verification and password reset emails are delivered through Brevo " +
        "(transactional email over HTTPS).",
      "Each of these providers has its own privacy policy and terms.",
    ],
  },
  {
    heading: "Please do not upload sensitive material",
    paragraphs: [
      "Do not upload confidential, regulated, or personal information about other people. " +
        "Good candidates are public documents, sample files, or notes you wrote yourself.",
      "Hosting uses an ephemeral disk, so uploaded files can disappear on any redeploy. " +
        "Treat nothing here as durable storage or as a backup.",
    ],
  },
  {
    heading: "Deleting your data",
    paragraphs: [
      "You can remove a document, clear a chat's memory, or delete a chat at any time. " +
        "Deleting a document also removes its file and its indexed chunks.",
      "There is no self-service account deletion yet. If you want your account and all " +
        "its data removed, contact me through the GitHub or LinkedIn links on the sign-in " +
        "screen and I will delete it.",
    ],
  },
  {
    heading: "Fair use limits",
    paragraphs: [
      "Questions are capped in length, and asks are limited per visitor per day so API " +
        "costs stay reasonable. Hitting the limit is expected behavior, not a failure.",
      "Please do not use this demo for automated scraping, load testing, or anything " +
        "abusive or unlawful.",
    ],
  },
  {
    heading: "No warranty",
    paragraphs: [
      "Answers are generated by language models and can be incomplete or wrong, even when " +
        "citations are shown. Verify anything that matters against the cited source.",
      "This demo is provided as is, without warranty, and it may change or go offline at " +
        "any time.",
    ],
  },
  {
    heading: "Attribution",
    paragraphs: [
      "Product and company names shown in this app identify the tools used to build it. " +
        "They are not sponsors, and they do not endorse this project.",
    ],
  },
];

/** Shown next to the upload control. */
export const UPLOAD_SENSITIVE_WARNING =
  "Please do not upload confidential or sensitive documents. Uploaded text is sent to the " +
  "model provider to answer your questions, and demo storage is ephemeral.";
